#!/bin/bash
# System Update
# ----------------------------
#       System Upgrade
# Snapshots - Rollback - Btrfs
# ----------------------------

SUDO=/usr/bin/sudo
MV=/usr/bin/mv
BTRFS=/usr/bin/btrfs
MOUNT=/usr/bin/mount
UMOUNT=/usr/bin/umount
SED=/usr/bin/sed
PACMAN=/usr/bin/pacman
TRIZEN=/usr/bin/trizen
CP=/usr/bin/cp
REFLECTOR=/usr/bin/reflector


####################################################
#------------------ LOGGING -----------------------#
# Log Date ----------------------------------------#
date >> /tmp/update.log
# Log Input and Output with tee -a /tmp/update.log #
####################################################

#---------------------------#
#      check Internet       #
#---------------------------#

check_internet()
{
  tool='curl'
  tool_opts='-s --connect-timeout 8'

  if ! $tool $tool_opts https://microsoft.com/ > /dev/null 2>&1; then
    err "You don't have an Internet connection!"
  fi

  return $SUCCESS
}


#--------------------------#
#     Snapshot - System    #
#--------------------------#

# ------ OLDSTABLE ------- #
$SUDO $BTRFS subvolume delete /.snapshots/OLDSTABLE
$SUDO $MV /.snapshots/STABLE /.snapshots/OLDSTABLE
$SUDO $SED -i 's/STABLE/OLDSTABLE/g' /.snapshots/OLDSTABLE/etc/fstab
$SUDO $CP /boot/vmlinuz-linux-stable /boot/vmlinuz-linux-oldstable
$SUDO $CP /boot/initramfs-linux-stable.img /boot/initramfs-linux-oldstable.img

# -------- STABLE -------- #
$SUDO $BTRFS subvolume snapshot / /.snapshots/STABLE
$SUDO $SED -i 's/TESTING/STABLE/g' /.snapshots/STABLE/etc/fstab
$SUDO $CP /boot/vmlinuz-linux /boot/vmlinuz-linux-stable
$SUDO $CP /boot/initramfs-linux.img /boot/initramfs-linux-stable.img

# -------------------------#
#      Update System       #
# -------------------------#
$SUDO $REFLECTOR --verbose -l 5 -p https --sort rate --save /etc/pacman.d/mirrorlist
$SUDO $PACMAN -Syu --color auto

# --- Verweiste Pakete entfernen --- #
#$SUDO $PACMAN -Rns $(pacman -Qtdq)

# -------------------------#
#    Balance Filesystem    #
# -------------------------#
$SUDO $BTRFS balance start -dusage=5 /btrfs | tee -a /tmp/update.log

# write end date to update.log
date >> /tmp/update.log
echo "   --> Ende des Updatevorganges" | tee -a /tmp/update.log

# Copy Log to ~/.update.log
cat /tmp/update.log >> ~/.local/share/update.log
rm /tmp/update.log
